### PR TITLE
shard 0.5.1

### PR DESCRIPTION
**Pull request by kbrock**
Thanks for creating these

--Keenan

### CODE REVIEW

**Comment by waj** [comment]
I'm sorry I didn't see your PR and updated the package. Note that now when you install `crystal-lang` it also includes shards unless `--without-shards` is specified.

**Comment by kbrock** [comment]
@waj installing shards **with** crystal is a great solution. thanks

**Comment by kbrock** [comment]
1. uninstalled shards and crystal-lang.
2. brew update
3. Installed crystal-lang.
4. shards # command not found

not sure how to brew update this repo.
Guess when the next version of crystal comes out it will be fixed.

**Comment by waj** [comment]
This should be working already, no need to wait for the next version. `brew update` should be updating all the taps, including manastech's.

A little more info could be helpful, like install output using `--verbose`.

**Comment by waj** [comment]
Also, consider opening a new issue if you think there is a bug in the formula.

**Pull request closed without merging**
