### PR TITLE
include llvm recipe to make it easier to get started

### PR DESCRIPTION
**Pull request by yyyc514**

### CODE REVIEW

**Comment by yyyc514** [comment]
The idea being that the "from source" for Mac instructions could be updated to be:

```
brew tap ...
brew install crystal --with-everything
```

This bundles a recipe for LLVM 3.5.1 that applies the correct patch.  We could go back to LLVM 3.5.0 if it's absolutely required but with the patch all the specs pass after compiling so I'm assuming 3.5.1 + the patch is solid.

Thoughts?

**Comment by yyyc514** [comment]
Or if better separation was desired we could have a separate "crystal-dev" brew that was simply "crystal-with-everything"... I'm mostly just wanting to make this "just work" for mac users.  Since we already support homebrew for installing the compiled I'm not sure why not to go this little bit further and support getting a whole working build setup in place.

**Comment by yyyc514** [comment]
If this is accepted I can alter my Makefile patch to first try llvm35-patched then fall back to whatever secondary choice is desired.

**Comment by yyyc514** [comment]
We could also just call it `llvm` but I thought `llvm35-patched` was best to avoid conflicts with other installs of LLVM that user might use for other things.

**Comment by waj** [comment]
So sorry for replying soooo late. I rebuilt this formula from scratch and now it depends on the official "llvm" formula. Thanks anyway!

**Pull request closed without merging**
